// app/layout.jsx
import "@/styles/globals.css";
import { Inter } from "next/font/google";
import Providers from "@/components/Providers";
import Navbar from "@/components/Navbar";
import Sidebar from "@/components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          {/* Navbar fijo */}
          <header className="fixed top-0 left-0 right-0 h-16 z-50">
            <Navbar />
          </header>

          <div className="flex">
            {/* Sidebar fija */}
            <aside className="fixed top-16 left-0 w-64 h-[calc(100vh-4rem)] z-40">
              <Sidebar />
            </aside>

            {/* Main con márgenes para respetar header y sidebar */}
            <main className="flex-1 ml-64 pt-16 min-h-screen bg-white overflow-y-auto">
              {children}
            </main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
